from __future__ import annotations

from enum import StrEnum


class MemoryScope(StrEnum):
    PERSONAL = "PERSONAL"
    SHARED_EVENT = "SHARED_EVENT"
    TESTIMONY = "TESTIMONY"
    WORLD_TESTIMONY = "WORLD_TESTIMONY"
    RUMOR = "RUMOR"
    TRAVELER_OBSERVATION = "TRAVELER_OBSERVATION"
    CONFIRMED_FACT = "CONFIRMED_FACT"


class MemoryTrust(StrEnum):
    CONFIRMED = "CONFIRMED"
    OBSERVED = "OBSERVED"
    PLAYER_SAID = "PLAYER_SAID"
    OTHER_CHARACTER_SAID = "OTHER_CHARACTER_SAID"
    RUMOR = "RUMOR"
    CORROBORATED_RUMOR = "CORROBORATED_RUMOR"
    INFERENCE = "INFERENCE"
    DISPUTED = "DISPUTED"
    CONTRADICTED = "CONTRADICTED"
    RETRACTED = "RETRACTED"
    UNVERIFIED = "UNVERIFIED"
    REDACTED = "REDACTED"


class AttributionMode(StrEnum):
    ATTRIBUTABLE = "ATTRIBUTABLE"
    ANONYMOUS = "ANONYMOUS"
    PRIVATE = "PRIVATE"


class DisclosureScope(StrEnum):
    PUBLIC = "PUBLIC"
    PRIVATE = "PRIVATE"
    GM_RESTRICTED = "GM_RESTRICTED"


class Confidentiality(StrEnum):
    PUBLIC = "PUBLIC"
    PRIVATE = "PRIVATE"
    GM_ONLY = "GM_ONLY"
    REDACTED = "REDACTED"


class LifecycleStatus(StrEnum):
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"
    REDACTED = "REDACTED"


class OpenThreadKind(StrEnum):
    PROMISE = "PROMISE"
    DEBT = "DEBT"
    OPEN_QUESTION = "OPEN_QUESTION"
    UNRESOLVED_CONFLICT = "UNRESOLVED_CONFLICT"
    PERSONAL_REQUEST = "PERSONAL_REQUEST"
    TRADE = "TRADE"
    FOLLOW_UP = "FOLLOW_UP"
    INVESTIGATION = "INVESTIGATION"
    UNVERIFIED_REPORT = "UNVERIFIED_REPORT"


class OpenThreadStatus(StrEnum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"
    BROKEN = "BROKEN"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    DISPROVED = "DISPROVED"


class MemoryRelationType(StrEnum):
    SAME_CHARACTER = "SAME_CHARACTER"
    SAME_SPEAKER = "SAME_SPEAKER"
    SAME_SUBJECT = "SAME_SUBJECT"
    SAME_ENTITY = "SAME_ENTITY"
    SAME_LOCATION = "SAME_LOCATION"
    SAME_QUEST = "SAME_QUEST"
    TEMPORAL = "TEMPORAL"
    PROMISE_RESULT = "PROMISE_RESULT"
    CAUSE_EFFECT = "CAUSE_EFFECT"
    CONFLICTS_WITH = "CONFLICTS_WITH"
    SUPPORTS = "SUPPORTS"
    RETRACTS = "RETRACTS"
    CONFIRMS = "CONFIRMS"
